Simplify immutability check

diff --git a/opensuse-migration-tool b/opensuse-migration-tool
--- a/opensuse-migration-tool
+++ b/opensuse-migration-tool
@@ -92,11 +92,6 @@ function populate_options() {
     done <<<"$versions"
 }
 
-# Check for Immutable OS
-mount | head -1 | grep rw 2>&1 > /dev/null
-RETCODE=$?
-
-# Check for Immutable OS
 mount | head -1 | grep rw 2>&1 > /dev/null || { echo "Please run the tool inside 'transactional-update shell' on Immutable systems."; exit 1; }
 
 # Elevated permissions check unless DRYRUN is set
@@ -105,6 +100,9 @@ if [ -z "${DRYRUN:-}" ]; then
         exec sudo "$0" "$@"
     fi
 fi
+
+# Requires elevated permissions or test will always fail
+test -w / || { echo "Please run the tool inside 'transactional-update shell' on Immutable systems."; exit 1; }
 
 # System-specific options
 if [[ "$NAME" == "openSUSE Leap Micro" ]]; then
